### ISSUE TITLE
Please set the path to the editor in the environment variable $EDITOR e.g. "export EDITOR=nano"

### ISSUE THREAD

**Issue by mazdafunsunn** [mborsetti/webchanges#1]
meanwhile urlwatch works as intended, webchanges unable to get $EDITOR variable.
![image](https://user-images.githubusercontent.com/3892223/101244404-11f15d80-370f-11eb-8d70-fd7b163b64c7.png)

python itself also is able to read this variable:
![image](https://user-images.githubusercontent.com/3892223/101245844-58978580-3718-11eb-8ca7-3bc6bc61f8f6.png)

**Comment by mborsetti** [comment]
Thanks 🙇, and apologies!

Found bug in the new logic automating editing in Windows (i.e. defaults to built-in notepad.exe if the EDITOR environment variable is not set). Just fixed in release 3.0.2., now available in PyPi.
