### ISSUE TITLE
Live job example

### ISSUE THREAD

**Issue by verlanmar** [mborsetti/webchanges#11]
Hello Mike,

Thank you for your excellent project!

I'd like to request if you would please consider adding to the Documentation a live full job example on how to cleanly monitor this page, below, for new releases:

https://github.com/mborsetti/webchanges/releases

It would help not very technically inclined users, such as me, to better learn about using the webchanges and content filtering strategies.

Thank you!

**Comment by mborsetti** [comment]
Thanks for the request.  

You can see some examples in the new 3.8 documentation [here](https://webchanges.readthedocs.io/en/stable/examples.html#watching-specific-sites).  The second entry is specifically about monitoring GitHub.

Would be grateful for feedback!
