### ISSUE TITLE
[BUG] Configuration check prevents using --edit-config

### ISSUE THREAD

**Issue by Markus00000** [mborsetti/webchanges#15]
**Describe the bug**
When `config.yaml` contains unrecognized options, a ValueError prevents fixing them using `webchanges --edit-config`.

**To Reproduce**
Add unrecognized options to `config.yaml` manually with an editor, then try to remove them using `webchanges --edit-config`.

**Expected behavior**
Fixing a broken configuration should always be possible with `--edit-config`. If the configuration check is run after saving `config.yaml`, it can still warn about unrecognized options that have not been fixed. Another possibility would be to show a prompt with a warning message when invoking `--edit-config` with an invalid configuration.

**Version info**
2021-08-03 08:55:26,577 cli DEBUG: webchanges: 3.8.1 Copyright 2020- Mike Borsetti
2021-08-03 08:55:26,577 cli DEBUG: Python: ('default', 'Jun 30 2021 10:22:16')
2021-08-03 08:55:26,580 cli DEBUG: System: Linux-5.13.7-arch1-1-x86_64-with-glibc2.33

**Comment by mborsetti** [comment]
I just released v3.8.2, which fixes this logic error.  Thanks so much for reporting it; very much appreciated! 🎉
