### ISSUE TITLE
[BUG] ValueError: Unrecognized directive(s) in the configuration file /home/user/.config/webchanges/config.yaml

### ISSUE THREAD

**Issue by c0deing** [mborsetti/webchanges#26]
**Describe the bug**
After upgrading from webchanges 3.8.3 to 3.9.1 i get the same error that has been described in #24 ("Check for typos", see below)
The thing is, that i have never used the webhooks reporter an i didn't change the config file at all before/after upgrading

**To Reproduce**
Hard to say. I just updated from 3.8.3 to 3.9.1 and boom, there was the error

**Expected behavior**
webchanges should run as usual

**Screen scrape/screenshots**
```

Traceback (most recent call last):
  File "/usr/local/bin/webchanges", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/webchanges/cli.py", line 232, in main
    urlwatch_command.run()
  File "/home/user/.local/lib/python3.8/site-packages/webchanges/command.py", line 675, in run
    self.urlwatcher.config_storage.load()
  File "/home/user/.local/lib/python3.8/site-packages/webchanges/storage.py", line 679, in load
    self.check_for_unrecognized_keys(config)
  File "/home/user/.local/lib/python3.8/site-packages/webchanges/storage.py", line 666, in check_for_unrecognized_keys
    raise ValueError(
ValueError: Unrecognized directive(s) in the configuration file /home/user/.config/webchanges/config.yaml:
report:
  webhook_markdown:
    enabled: false
    max_message_length: null
    webhook_url: ''
Check for typos (documentation at https://webchanges.readthedocs.io/)
```

**Version info**
Please run ``webchanges -v`` and paste the version information as follows (first 3 lines):
 - webchanges: 3.8.3 Copyright 2020- Mike Borsetti
 - Python: 3.8.10 ('default', 'Nov 26 2021 20:14:08') GCC 9.3.0
 - System: Linux-5.4.0-88-generic-x86_64-with-glibc2.29

**Additional context**
Actually, there is no hooks.py in config/webchanges/ 
Thanks in advance for helping me out!

Btw.: How do you manage to insert the info that there is a new version of webchanges into the telegram reporter messages? - just wondering :)

**Comment by mborsetti** [comment]
Truly sorry about that.  The error will be modified to a warning, so it won't impede a run (which it shouldn't be); it's useful to know if there's a typo, but not useful in this way.

Right now just delete the `webhook_markdown` entry from your configuration file; it's not a valid reporter (maybe it was one that had been defined in a hooks.py file, but because such file is not present, the system doesn't know about it).

> Btw.: How do you manage to insert the info that there is a new version of webchanges into the telegram reporter messages? - just wondering :)

100% pure magic!

Really appreciate the bug report!

**Comment by c0deing** [comment]
Thanks for the quick reply!
I commented out the `webhook_markdown` reporter and its working again!

> 100% pure magic!

Hm. Not very satisfying :)
I just thought maybe you are able to see/read the users reporter messages, that's why i asked. Feels a little scary tbh.

**Comment by mborsetti** [comment]
> Hm. Not very satisfying :) I just thought maybe you are able to see/read the users reporter messages, that's why i asked. Feels a little scary tbh.

Oh, gosh, absolutely no!  No data goes out; the code is all here to check.

It's a simple _read_ from PyPi to get the currently published version number, and, if it's higher than current, the addition of some text to the footnote.

**Comment by c0deing** [comment]
Alright then.
Thanks for the support!
