### ISSUE TITLE
[BUG] Config files creation ignoring home directory and $HOME/.config

### ISSUE THREAD

**Issue by Blocked** [mborsetti/webchanges#28]
**Describe the bug**
`webchanges` seems to check the root folder, creates and stores config files in the first accessible folder: `/data/data/com.termux/shared_prefs/webchanges/jobs.yaml`. `urlwatch` stores it correctly in ``XDG_CONFIG_HOME``:`$HOME/.config/urlwatch`. `$HOME` would be `/data/data/com.termux/files/home`. Migration fails.

**To Reproduce**
Run `webchanges` in a non standard prefixed environment.

**Expected behavior**
Default config files should be stored in `$HOME/.config/*`.

**Version info**
Please run ``webchanges -v`` and paste the version information as follows (first 3 lines):
 - webchanges 3.9.1
 - Python 3.10.2
 - System Linux-4.14-perf+-aarch64-with-libc(Termux/Android)

**Comment by mborsetti** [comment]
Thanks.  

The location is determined by a call to [platformdirs](https://github.com/platformdirs/platformdirs), and according to its [documentation ](https://platformdirs.readthedocs.io/en/latest/api.html#platformdirs.unix.Unix.user_config_dir) in Unix (Linux) it should be
> the config directory tied to the user, e.g. `~/.config/$appname/$version` or `$XDG_CONFIG_HOME/$appname/$version`.

appdirs is effectively unmaintained; platformdirs is the community's forked replacement.

**Comment by Blocked** [comment]
If I read the code correctly, it seems to always use `platformdirs`. Am I right? Does it always use `platformdirs` or only the first run and it saves it somewhere?

**Comment by mborsetti** [comment]
> If I read the code correctly, it seems to always use `platformdirs`. Am I right? Does it always use `platformdirs` or only the first run and it saves it somewhere?

Correct, it always uses `platformdirs` (never saves it); specifically, from `cli.py`:
```
    if os.name != 'nt':
        config_path = user_config_path(__project_name__)  # typically ~/.config/{__project_name__}
```
where `user_config_path` is imported from `platformdirs`

**Comment by Blocked** [comment]
Thanks. I guess this is a upstream issue.
