### ISSUE TITLE
Send email headers with initial uppercase to support case-sensitive email clients

### ISSUE THREAD

**Issue by fdelapena** [mborsetti/webchanges#29]
**Describe the bug**
Code using `msg['from']`, `msg['to']` and `msg['subject']` generate `from: `, `to: `, and `subject: ` headers respectively. Some email clients don't parse properly those headers.

**To Reproduce**
Email received in software like K-9 Mail or Mailnag don't parse email with initial lowercase headers and show empty values on received email.

It is suggested to use `msg['From']`, `msg['To']` and `msg['Subject']` to maximize compatibility.

**Comment by mborsetti** [comment]
Indeed!  Lowercase ones are not RFC compliant, as summarized in [RFC 2076](https://datatracker.ietf.org/doc/html/rfc2076).

Thanks for reporting; will be fixed in the next release.

**Comment by thp** [comment]
FYI, The upstream project (`urlwatch`) from which this was forked (see #30) doesn't have this bug.

**Comment by mborsetti** [comment]
> FYI, The upstream project (`urlwatch`) from which this was forked (see #30) doesn't have this bug.

Well played!

**Comment by mborsetti** [comment]
@fdelapena Finally found the time to do a release (3.9.2) with this fix; apologies for the delay and thanks again for the bug report!
