### ISSUE TITLE
[BUG] wait_for_timeout fails with integers

### ISSUE THREAD

**Issue by Markus00000** [mborsetti/webchanges#39]
**Describe the bug**

`wait_for_timeout` only works with floats, not integers.

**To Reproduce**

    wait_for_timeout: 8
    => ValueError: Job 1: Directive 'wait_for_timeout' can only be a number; found <class 'int'>.

    wait_for_timeout: 8.0
    => works

**Expected behavior**

Integers should work as numbers.

**Version info**

- webchanges: 3.10.1 Copyright 2020- Mike Borsetti
- CPython: 3.10.4 ('main', 'Mar 23 2022 23:05:40') GCC 11.2.0
- System: Linux-5.17.9-arch1-1-x86_64-with-glibc2.35

**Comment by mborsetti** [comment]
Thanks **Markus** for the report! 

Will be fixed in the next release (and thanks for the workaround).

**Comment by mborsetti** [comment]
Fixed in 3.10.2
