### ISSUE TITLE
better bot detection protection

### ISSUE THREAD

**Issue by amammad** [mborsetti/webchanges#45]
Hey man, I am using webchanges, and it is fantastic! 
What is your opinion about using **https://crawlee.dev/docs/quick-start**? It'll add a configuration layer for bot detection escape! It's really helpful, I think

**Comment by mborsetti** [comment]
I am not familiar with it but super supporting of anything that makes notifications/monitoring more useful, and like the bot detection escape angle of it.

However, it seems to lack a Python interface, so am a bit confused as to how it would be integrated.  Do you have any thoughts?

**Comment by mborsetti** [comment]
Thanks for the link to https://intoli.com/blog/not-possible-to-block-chrome-headless/.  Great stuff.

Release 3.11 is out, and all the suggestions have been implemented. Jobs using `use_browser: true` pass the test at https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

Thanks again for (indirectly) suggesting this!
