### ISSUE TITLE
Ignore report if filter/changes/diff = deleted[FEATURE] 

### ISSUE THREAD

**Issue by bbeevvoo** [mborsetti/webchanges#47]
I've tried empty_diff but it apparently does not work with webchanges. My jobs.py is setup so it checks a site for a specific  set of words that is added. I get a report when there is an addition as well as the changes. But when that set of words are removed I still get a notification. I would like to only be notified when the the line is added. 
kind: url

url: https:cantshowyou
ssl_no_verify: true
ignore_http_error_codes: 4xx, 5xx
diff_filter:
  - grep: '^[@+]'
filter:
  - re.sub: 
      pattern: 'playCheckinSound'
      repl: <br>
  - html2text:
      method: pyhtml2text
      unicode_snob: true
      body_width: 0
      inline_links: false
      ignore_links: true
      ignore_images: true
      pad_tables: false
      single_line_break: true
  - sort:
      separator: '<br>'
  - keep_lines_containing: '"status":1'
  - strip

```
-----------------------------------------------
display:
  new: true
  error: true
  unchanged: false
  empty-diff: true (returns Error)
report:
  alarm:
    enabled: true
    sound: ''

**Comment by mborsetti** [comment]
I am not totally sure, but I think you're looking for the [additions_only](https://webchanges.readthedocs.io/en/stable/diff_filters.html#additions-only) diff filter.

Please let me know.

**Comment by mborsetti** [comment]
The configuration setting `empty-diff` within the `display` configuration will be added in the next release for backwards-compatibility; if all goes well it will be out shortly.

**Comment by mborsetti** [comment]
Release 3.11 is out and it handles the configuration setting `empty-diff` within the `display` configuration will be added in the next release for backwards-compatibility.

@bbeevvoo Please let me know if you find any bugs with it.

Thanks for the report!
