### ISSUE TITLE
[FEATURE] Separate report per each job

### ISSUE THREAD

**Issue by drws** [mborsetti/webchanges#51]
**Is your feature request related to a problem? Please describe.**
Webchanges currently sends a single e-mail containing reports of all jobs that encountered changes.

**Describe the solution you'd like**
It would be very useful if one was able to set per-job e-mail generation. In this manner user was notified with multiple e-mails if multiple jobs encountered changes. This is important for further e-mail filtering for example as well as for manageable _Subject_ lengths.

**Describe alternatives you've considered**
Running multiple `webchanges` instances, but it is counterproductive.

**Comment by mborsetti** [comment]
This sounds useful; thanks for proposing it.

Have you given any thought as to its implementation architecture?  E.g. where would the indication of "per-job [report] generation" would live, would this be for all jobs in the run, etc. etc.?

**Comment by drws** [comment]
I see it as a general reporting feature that should be available in any type of report (text, HTML or MD). Configuration-wise it could be available under each type, similar to parameter `minimal` (available for text and MD).

```
report:
  text:
    individual: true
    minimal: true
    ...
```

I think a global parameter that affects all jobs in the run would suffice. If a more fine-grained control is desired by the user then multiple instances is the answer given the current `webchanges` architecture. If finer control is implemented here, there are many more similar options that should allow per-job configuration and we'd be quickly looking at major reworks.

**Comment by mborsetti** [comment]
Reports have a new ``separate`` configuration option to split reports into one-per-job.

Please see documentation here https://webchanges.readthedocs.io/en/stable/reports.html#text

**Comment by pawelpbm** [comment]
@mborsetti I think this doc also needs to be updated (also it mentiones urlwatch not webchanges)? https://webchanges.readthedocs.io/en/stable/advanced.html#creating-a-separate-notification-for-each-change

**Comment by mborsetti** [comment]
Ooops, thanks for reporting this!  Will be fixed at the next release.
