### ISSUE TITLE
[FEATURE] Command line option to append custom message to reports

### ISSUE THREAD

**Issue by drws** [mborsetti/webchanges#55]
**Is your feature request related to a problem? Please describe.**
It would come in very handy to be able to append a custom message that was displayed somewhere in the report.

**Describe the solution you'd like**
For example: `webchanges -m "Append this message to reports."`
If set, all triggered report(er)s would append the message (to the top of the report for example).

**Describe alternatives you've considered**
None that would be clean solutions.

**Comment by mborsetti** [comment]
Love it!

Queued when I have free time...hopefully soon!

**Comment by mborsetti** [comment]
With version 3.13 just released, there is a new command line argument ``--footnote`` to add a custom footnote to reports.

See documentation at https://webchanges.readthedocs.io/en/stable/cli.html#add-a-footnote-to-your-reports
