### ISSUE TITLE
[BUG] Monitor web in angular js

### ISSUE THREAD

**Issue by AntonioCatalanSanchez** [mborsetti/webchanges#56]
hello, I'm trying to monitor a url that is made in angular js, but I only detect the text of the <title></title> tags, I do not know how to do to catch everything inside the body and <app-root> tags that is where is really all the content of the web.
I leave the configuration here:

name: ecopetrol.taskgo.co
kind: url
url: https://ecopetrol.taskgo.co
use_browser: true
max_tries: 2
filter:
  - re.sub:
      pattern: <styleb[^>]*>([\s]*?)</style>.
      repl: ''
  - re.sub:
      pattern: <noscriptb[^>]*>([\s\S]*?)</noscript>
      repl: ''
  - re.sub:
      pattern: <scriptb[^>]*>([\s\S]*?)<\/script>.
      repl: ''
  - html2text:
      method: re

config.yaml:
# webchanges configuration file. See https://webchanges.readthedocs.io/
# Written on 2023-01-31T11:28:38 using version 3.11

display:
  error: true
  new: true
  unchanged: true
report:
  html:
    diff: table
  post:
    enabled: true
    details: true
database:
  engine: sqlite3
  max_snapshots: 1
job_defaults:
  all:
    use_browser: true
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.119 Safari/537.36
    diff_tool: /home/antoniocs88/projects/Monitor-backend/monitor/management/commands/urlwatchdiff.sh
    ignore_connection_errors: false
    ignore_timeout_errors: false
    ignore_too_many_redirects: false
    ignore_http_error_codes: false
    ssl_no_verify: true
    max_tries: 2
    timeout: 5

I have already tried many things and I can't find it, I don't know if you can answer me. Thank you very much anyway.

**Comment by mborsetti** [comment]
How about starting with a basic configuration?

```
name: ecopetrol.taskgo.co
url: https://ecopetrol.taskgo.co/home
use_browser: true
filter:
  - html2text:
```

Will give this output:
```
ecopetrol.taskgo.co
-------------------

1
Felipe Bayón
Administrador
[ Home ](https://ecopetrol.taskgo.co/home)[ Visualización Datos ](https://ecopetrol.taskgo.co/field-list)[ Datos Disponibles ](https://ecopetrol.taskgo.co/available-data)[ Roles Usuarios ](https://ecopetrol.taskgo.co/user-roles)[ Alertas y Notificaciones ](https://ecopetrol.taskgo.co/notifications)
Visualización Datos Graficacion de las fuentes de datos de modelo HOPE VisualizarDatos Disponibles Modelos de datos disponibles para visualización VisualizarRoles Usuarios Permisos y usuarios disponibles para ingreso a la plataforma VisualizarAlertas Y Notificaciones Alertas generadas por la plataforma de acuerdo a la información ingresada Visualizar

--
Job tested in 4.7 seconds with webchanges 3.12
```

You can then read the [documentation](https://webchanges.readthedocs.io/) and refine what you want.
