### ISSUE TITLE
Question: How to re-process old changes?

### ISSUE THREAD

**Issue by knutwannheden** [mborsetti/webchanges#57]
(Since the Discussions feature isn't enables for this repo, I report this question as an issue. Forgive me if this is the wrong way to do this!)

I would like to re-process some recent changes recorded by `webchanges`. My use case is that for a while the reporting via one channel failed. Now this has been fixed, but I would like to trigger the reporting again for a given time period. If there isn't any such feature already, I would be completely OK with doing this via Python APIs. Can you give me some hints on how to do this?

**Comment by mborsetti** [comment]
Hello Knut,

Firstly, thanks for the hint on the GitHub Discussions feature; it's now turned on!

I'd start with ``--test-diff`` along with ``--test-reporter`` as per [here](https://webchanges.readthedocs.io/en/stable/cli.html#show-diff-from-saved-snapshots) and/or ``--rollback-database`` (see [here](https://webchanges.readthedocs.io/en/stable/cli.html#rollback-the-database)), depending on your exact use case.
