### ISSUE TITLE
additions_only: true  , but still receive alert when no matched content found

### ISSUE THREAD

**Issue by Fedora7** [mborsetti/webchanges#6]
I have additions_only: true in job config. When the matched content reduced from one found to nothing found, I received alert of the following. In this case, no addition is really found. Is this the expected behavior ? Thanks.

`---------------------------------------------------------------------------
CHANGED: index · web...  ( http://..../ )
---------------------------------------------------------------------------

+++ @	Mon, 19 Apr 2021 16:02:01 -0700
---------------------------------------------------------------------------

--
Checked 1 source in 0.066 seconds with webchanges 3.4.1`

**Comment by mborsetti** [comment]
I have seen reports consisting entirely of a new empty line; not sure if it's the case here.

At the moment _all_ additions get reported, even if it's new empty lines. Let me know if you think it may be useful to change this behavior.

**Comment by Fedora7** [comment]
In most of my cases, I list the new things ( new product, new topic, new discussion thread, new video, etc ) that I am interested under additions_only and trigger the alert email to my phone. But these supposed to be exciting alerts became annoying.  Since half of them are not about new things happening. The new things/events on web come and go quickly. If I want to know they are gone, I always have the option to use deletions_only directive or simply use diff_filter: grep: '^\+' . The current behavior make the new shining feature of additions_only less useful. I vote for not reporting item that is gone if it's under additions_only. Thanks.

**Comment by mborsetti** [comment]
Agree.  If anyone is interested in cosmetic changes they would not be using `additions_only` to begin with.

Will change the behavior of the filter to not report changes if they only consist of addition of blank lines.

Thanks for the report!

**Comment by mborsetti** [comment]
> Will change the behavior of the filter to not report changes if they only consist of addition of blank lines.

Version 3.5, just released, incorporates this improvement.

Thank you very much for opening an issue!
