### ISSUE TITLE
[FEATURE]  `webchanges --errors` should use reporters

### ISSUE THREAD

**Issue by yubiuser** [mborsetti/webchanges#63]
**Is your feature request related to a problem? Please describe.**
I think `webchanges --errors` is a great feature. However, it only reports to `stdout`

**Describe the solution you'd like**
If it would use the configured reporters, one could put `webchanges --errors` in a cron job and check for errors and empty filters e.g. once a week automatically.

**Describe alternatives you've considered**
Run the command from time to time manually - and forget about it at some point

**Comment by mborsetti** [comment]
Great idea!

Will definitely implement this -- I too am using the alternative, including forgetting about it at some point! ;)

**Comment by yubiuser** [comment]
Looking forward to the implementation.

**Comment by mborsetti** [comment]
I just released work already in progress; this will be next.

**Comment by mborsetti** [comment]
Released in v3.17.

**Comment by yubiuser** [comment]
Really nice. Tested it and worked as expected.

![Screenshot_20231210-202840](https://github.com/mborsetti/webchanges/assets/26622301/11f9da6a-b4ba-44f0-903e-26ef84fba0cf)
