### ISSUE TITLE
[FEATURE] webchanges docker available

### ISSUE THREAD

**Issue by yubiuser** [mborsetti/webchanges#64]
Thanks for providing such a nice "upgrade" to `urlwatch`

Just wanted to let you know, I created a small docker image that runs `webchanges` periodically. I use `pyinstaller` to create a standalone executable and a `alpine` base which allows for a small image (~30 MB). 
You can find the repo at https://github.com/yubiuser/webchanges-docker

Feel free to try it and link it somewhere if you find it useful.

**Comment by yubiuser** [comment]
> I assume you don't mind if I link there from the documentation?

Please do so :-)

**Comment by mborsetti** [comment]
Out in version 3.16 -- thanks!  https://webchanges.readthedocs.io/en/stable/index.html#running-in-docker
