### ISSUE TITLE
[BUG] v3.18 reporting `empty-diff` as unrecognised 

### ISSUE THREAD

**Issue by yubiuser** [mborsetti/webchanges#67]
As of v3.18 I get warnings every time I start `webchanges` about `display/empty-diff` being unrecognised. However, the changelog did not mention this option being removed.

```
webchanges/storage.py:711: RuntimeWarning: Found unrecognized directive(s) in the configuration file config.yaml:
display:
  empty-diff: true
Check for typos (documentation at https://webchanges.readthedocs.io/)
```

**Comment by yubiuser** [comment]
Went through the code changes and saw that the option was renamed to include an underscore instead of a hyphen. `emoty_diff`.

This is not documented in the release notes. Why was it renamed at all?

**Comment by mborsetti** [comment]
Ouch! 

It was a temporary fix to the "**invalid signature for autoattribute ('webchanges.storage::ConfigDisplay.empty-diff') don't know which module to import for autodocumenting 'webchanges.storage::ConfigDisplay.empty-diff'**" error, which wasn't supposed to go out.  Will regress.

Apologies.
