### ISSUE TITLE
[Discussion] Disabled jobs should not be tested by --errors

### ISSUE THREAD

**Issue by yubiuser** [mborsetti/webchanges#73]
I have a few disabled jobs (`enabled: false`) because they (currently) don't work (e.g. 404). Once a day I run `--errors` which will also test the disabled jobs and report errors of those. This is kind of annoying, because I already know they don't work - which was the reason to disable them in the first place.

I think disabled jobs should not be checked for errors

**Comment by mborsetti** [comment]
Thanks for taking the time to report this; completely agree.  I will look into making the changes for the next release.

**Comment by mborsetti** [comment]
Implemented in 3.21
