### ISSUE TITLE
[FEATURE] Store snapshots in $XDG_DATA_HOME by default

### ISSUE THREAD

**Issue by Markus00000** [mborsetti/webchanges#75]
**Is your feature request related to a problem? Please describe.**
By default, snapshots are stored in `~/.cache/webchanges/`. I expect cache contents to speed up future computations and to be either a copy of data elsewhere or something that can be computed again. However, snapshots do not speed up future runs, the data might not be stored elsewhere any longer and cannot be computed again as web content changes. I see snapshots as user data and not as cached data.

For many jobs I have memorized the content. The next diff makes sense because it is a comparison to the previous snapshot that I have memorized. If I lose the previous snapshot, I have to re-read the content and compare it to my memory. This can be time consuming and difficult.

I exclude `~/.cache/` from most backups as I expect it is not user data. For example, moving to a new computer and not migrating `~/.cache/` would cause me to lose all snapshots.

**Describe the solution you'd like.**
Store the snapshot database in `$XDG_DATA_HOME`, which by default is `~/.local/share/`.

**Comment by mborsetti** [comment]
Hi Markus,

Thanks for a great, complete and well-reasoned requests. I agree 💯  with you; the legacy directory makes little sense.

Thanks for the contribution; it will be implemented in an upcoming release.

**Comment by mborsetti** [comment]
Implemented in 3.22, just released.

Thanks for the suggestion!
