### ISSUE TITLE
[BUG] DB not closing properly when SMTPDataError happens

### ISSUE THREAD

**Issue by pawelpbm** [mborsetti/webchanges#77]
**Describe the bug.**
I believe that DB is not getting closed properly when there is an issue with email delivery.

I observed it recently: I have a bunch of URLs to check daily. After few of them made some changes I started getting emails about the same changes every day - every day I was getting diff between today's check and some day in Nov when the page was modified the previous time.

After some testing I noticed that one of the URLs is failing delivery because content of the email is getting rejected by GMail:

```
smtplib.SMTPDataError: (552, b'5.7.0 This message was blocked because its content presents a potential\n5.7.0 security issue. To review our message content and attachment content\n5.7.0 guidelines, go to\n5.7.0  https://support.google.com/mail/?p=BlockedMessage XXXX - gsmtp')
```

When I added filter to this page to only include very specifc parts of it, the email got delivered and after one more run all the other pages reported no changes.

In output of `webchanges -v` when running without the problematic page, I noticed that one of the last steps is "Closing DB connection", so my guess is that this is not happening properly when the above message shows.

**Steps to reproduce.**
Confing with the "problematic" page:
````
name: "TEST"
url: https://pttk.myslenice.pl/myslenickie-szlaki-2/#
filter:
  - absolute_links
````

I'm guessing GMail is not happy about some of the JS in the page code.

**Version info.**
````
Software:
• webchanges: 3.21
• CPython: 3.11.2 ('main', 'Mar 13 2023 12:18:29') GCC 12.2.0
• SQLite: 3.40.1

Installed PyPi dependencies:
• beautifulsoup4: 4.12.3
• cssselect: 1.2.0
• h2: 4.1.0
  - hyperframe: 6.0.1
  - hpack: 4.0.0
• html2text: 2024.2.26
• httpx: 0.27.0
  - anyio: 4.3.0
  - certifi: 2024.2.2
  - idna: 3.7
  - sniffio: 1.3.1
• lxml: 5.2.1
  - cssselect: 1.2.0
  - BeautifulSoup4: 4.12.3
• markdown2: 2.4.13
• msgpack: 1.0.8
• platformdirs: 4.2.0
• pyyaml: 6.0.1
• requests: 2.31.0
  - charset-normalizer: 3.3.2
  - idna: 3.7
  - urllib3: 2.2.1
  - certifi: 2024.2.2
````

It was the same on 3.15.

**Comment by mborsetti** [comment]
Hello Paweł,

This is actually by design.  

SInce most common implementation is with a single reporter, if the reporter fails then the user is not notified of the changes.

If we don't save the snapshot, then once the reporter is fixed the user will be notified of all changes since the last report he/she saw; otherwise some of the changes may be missed as the snapshots get replaced while the reporter is broken; the logic implemented prevents this from happening.

If you feel it's incorrect, please share your thoughts!

**Comment by pawelpbm** [comment]
In my case I have separate emails per each URL (`separate: true` in the config). In this case I only one delivery was failing so I was getting the same reports every day for all other jobs. Maybe in this case webchanges should only not save the failing deliveries?

Also, I know that this error is probably very specific to GMail, and this might be a really edge case, but in case of multiple emails if one is failing and others are not and this error is seen, there could be actually notification about it emailed to the address. But I feel like this might be to comlicated and too edge case to actually implement...

**Comment by mborsetti** [comment]
> But I feel like this might be to complicated and too edge case to actually implement...

Agreed ... that would be a ton of work, sorry!
