### ISSUE TITLE
webchanges.yaml file missing - can't configure reporters

### ISSUE THREAD

**Issue by rtfgvb01** [mborsetti/webchanges#8]
Project is very cool. Thanks

Had a rough go getting webchanges installed and running properly on Ubuntu 18.04. After install, there was no /webchanges/ directory in the /.config/ folder. I created that, and also created the jobs.yaml and config.yaml files. After that, I was able to successfully create and test some jobs. However, now I've gone to set up a reporter. Following the docs:

You can change the settings to add or change where the report is sent to. Settings are contained in the configuration file webchanges.yaml, a text file located in the ~\.urwatch\ directory (Linux) 

There is no such directory on my machine. I tried creating one, and then creating the webchanges.yaml file, but upon running webchanges --test-reporter webhook it reported as not being enabled (I'm guessing it's not reading that file).

Any suggestions here?

Thanks

**Comment by rtfgvb01** [comment]
So I was planning to get on with my evening after a couple hours but had to keep playing around. I got it to work after some likely YAML tricker by sticking it in the /.config/webchanges/config.yaml file. Could be helpful for amateurs like me to expand on setting up reporters in the documentation.

**Comment by mborsetti** [comment]
Hello @rtfgvb01,

Thanks for reporting your difficulties.  The method of installing _webchanges_ was inherited from the upstream project, and these are the instructions from README:

> Run `webchanges --edit` to customize your jobs list (this will also create _jobs.yaml_ and _config.yaml_)
> Run `webchanges --edit-config` if you want to set up e.g. e-mail sending

Your issue post highlighted that it's pretty unfriendly and will work on automating the creation of those files at installation (if possible to do so), which makes it much user friendly.  In the interim will add some verbiage in the documentation as you suggestged.

Thanks for taking the time to report your experience.

**Comment by mborsetti** [comment]
Version 3.5, just released, automates the creation of the jobs and configuration files (at first run, even without using the `--edit` command line argument), and its documentation has been updated with the correct file and directory names plus some additional description.

Thank you very much for opening an issue!
