### ISSUE TITLE
[FEATURE] Filter to get first or last line

### ISSUE THREAD

**Issue by mhalano** [mborsetti/webchanges#81]
**Is your feature request related to a problem? Please describe.**
I use webchanges to query Debian packages versions that are available in the repository using re.findall and RegEx groups, but it returns plenty of lines, and sometimes I just want the first line or the last one.

**Describe the solution you'd like.**
An option like `first_line` and `last_line` to filter just one of these lines.

**Describe alternatives you've considered.**
I tried using RegEx but couldn't find a suitable parameter.

**Additional context.**
For example, with this query I just want the last line that show the newer version.
![image](https://github.com/mborsetti/webchanges/assets/6025031/5179ec45-6766-413b-9edb-680bcb9ae374)

**Comment by mborsetti** [comment]
Great idea!

**Comment by mborsetti** [comment]
> For example, with this query I just want the last line that show the newer version.

You can keep the query as is and use ``additions_only``; that will notify if a new line is added at the bottom, as it will have a new version number.

On second thought, I am not sure if that filter is really needed; is there another use case?

**Comment by mhalano** [comment]
> > For example, with this query I just want the last line that show the newer version.
> 
> You can keep the query as is and use `additions_only`; that will notify if a new line is added at the bottom, as it will have a new version number.
> 
> On second thought, I am not sure if that filter is really needed; is there another use case?

I mean in the screenshot. So instead of appear two lines, like in the screenshot, it would just appear "0.9.5-2", the line I want to check for changes. Got it?

**Comment by mhalano** [comment]
Like if you have a page that shows, let's say, 5 items, and when a new item appears it becomes the first, or the last, item and one item disappears because it's shows just 5 items.
In this case, it would be more useful to just get the first, or the last, item, the one that updates, even you could get all the 5 items because you could keep an eye on the item value.

**Comment by mborsetti** [comment]
Good news: it turns out you can write Regexes to do this, and apply the ``re.findall`` filter.  

See [new examples](https://webchanges.readthedocs.io/en/stable/filters.html#re-findall:~:text=to%20extract%20the%20first%20line%3A) in the documentation for v3.24 just released.
