### ISSUE TITLE
[BUG] ImportError: Python package 'minidb' is not installed; cannot upgrade the legacy 'minidb' database

### ISSUE THREAD

**Issue by adriangalilea** [mborsetti/webchanges#82]
After install in mac using pipx.

**Comment by mborsetti** [comment]
You probably had urlwatch installed at some point (but no longer have it, hence the missing `minidb` library).

You can either delete its database file (should be in `/Users/trentm/Library/Caches/urlwatch`) or manually install `minidb` to allow the upgrade to go through:
```
pip -U install minidb
```
(or the pipx equivalent, but am not familiar with it)

**Comment by adriangalilea** [comment]
I did not have it installed, I used `urlwatch` before.

I came to this after noticing javascript support, but I couldn't make it work on my target.

**Comment by mborsetti** [comment]
Oh. Can you please run `webchanges -vv` and paste the output?

**Comment by adriangalilea** [comment]
I won't be able to do it today, but the URL was: https://platform.openai.com/docs/changelog

**Comment by mborsetti** [comment]
Did installing `minidb` fix the issue? It's required to convert the `urlwatch` database.

BTW, thanks for the feedback; I will add clearer instructions in the error message.

**Comment by adriangalilea** [comment]
> Did installing `minidb` fix the issue? It's required to convert the `urlwatch` database.

Yes installing `minidb` fixed it, unfortunately after trying to scrape the URL and not being able I desisted  :)
