### ISSUE TITLE
[BUG] Deploy action is out of date and unmaintained

### ISSUE THREAD

**Issue by yubiuser** [mborsetti/webchanges#85]
The action you use for deployment is unmaintained since 2021. (https://github.com/actions/create-release). You should consider to switch to a maintained one (e.g. https://github.com/softprops/action-gh-release).

Currently, your workflow fail: https://github.com/mborsetti/webchanges/actions/runs/11312286058

**Comment by mborsetti** [comment]
Hi @yubiuser,

Thanks so much for your contribution!  Yeah, I caught this, and manually pushed _this_ release but fixed the code for future ones.   And guess what ... of the various options, I also picked softprops!

Thanks so VERY much for catching this and for the recommendation!
